const NO_DATA = 0, LOADING = 1, LOADED = 2;
const ADD_ITEM = 'ADD_ITEM';
const ITEM_FETCH_DATA = 'ITEM_FETCH_DATA';
const FETCH_FAILED = 'FETCH_FAILED';
const FETCH_GOT_DATA = 'FETCH_GOT_DATA';
const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
const UNDO_ITEM = 'UNDO_ITEM';
const ADD_ADMIN_ITEM = 'ADD_ADMIN_ITEM';
const UNDO_ADMIN = 'UNDO_ADMIN';
const REDO_ITEM = 'REDO_ITEM';
const ADD_REMOVED_ITEM = 'ADD_REMOVED_ITEM';
const UNDO_REMOVED_ITEM = 'UNDO_REMOVED_ITEM';
const REDO_REMOVED_ITEM = 'REDO_REMOVED_ITEM';

export {NO_DATA, LOADING, LOADED, ADD_ITEM, ITEM_FETCH_DATA, FETCH_FAILED, FETCH_GOT_DATA, UPDATE_QUANTITY, UNDO_ITEM, ADD_ADMIN_ITEM, UNDO_ADMIN, REDO_ITEM, ADD_REMOVED_ITEM, UNDO_REMOVED_ITEM, REDO_REMOVED_ITEM};
