const NO_DATA = 0, LOADING = 1, LOADED = 2;
const ADD_ITEM = 'ADD_ITEM';
const ITEM_FETCH_DATA = 'ITEM_FETCH_DATA';
const FETCH_FAILED = 'FETCH_FAILED';
const FETCH_GOT_DATA = 'FETCH_GOT_DATA';

export {NO_DATA, LOADING, LOADED, ADD_ITEM, ITEM_FETCH_DATA, FETCH_FAILED, FETCH_GOT_DATA};
